"use strict";
const $ = s => document.querySelector(s), $$ = s => [...document.querySelectorAll(s)];
const store = { get: (k, f) => { try { return JSON.parse(localStorage.getItem(k)) ?? f } catch { return f } }, set: (k, v) => localStorage.setItem(k, JSON.stringify(v)) };
let tasks = store.get("studybalance_tasks", []), sessions = store.get("studybalance_sessions", 0), timerSeconds = 1500, timerId = null, timerRunning = false;
const today = () => new Date().toISOString().split("T")[0];
$("#todayDate").textContent = new Date().toLocaleDateString("en-GB", { weekday: "long", day: "numeric", month: "long" });
$("#taskDate").min = today(); $("#taskDate").value = today();
function toast(message) { const el = $("#toast"); el.textContent = message; el.classList.add("show"); setTimeout(() => el.classList.remove("show"), 2200) }
function go(page) { $$('.page').forEach(x => x.classList.toggle('active', x.id === page)); $$('.nav-item').forEach(x => x.classList.toggle('active', x.dataset.page === page)); $("#pageTitle").textContent = $(`.nav-item[data-page="${page}"] span`).textContent; $("#sidebar").classList.remove("open"); window.scrollTo({ top: 0, behavior: "smooth" }); if (page === "deadlines") renderDeadlines() }
$$('.nav-item').forEach(b => b.onclick = () => go(b.dataset.page)); $$('[data-go]').forEach(b => b.onclick = () => go(b.dataset.go)); $("#menuButton").onclick = () => $("#sidebar").classList.toggle("open");
const dialog = $("#taskDialog"); $$('[data-open-task]').forEach(b => b.onclick = () => dialog.showModal()); $("#closeDialog").onclick = () => dialog.close();
$("#taskForm").onsubmit = e => { e.preventDefault(); tasks.unshift({ id: Date.now(), title: $("#taskTitle").value.trim(), module: $("#taskModule").value.trim(), date: $("#taskDate").value, priority: $("#taskPriority").value, completed: false }); store.set("studybalance_tasks", tasks); e.target.reset(); $("#taskDate").value = today(); dialog.close(); renderAll(); toast("Task added successfully") };
function daysUntil(date) { const a = new Date(today() + "T00:00:00"), b = new Date(date + "T00:00:00"); return Math.round((b - a) / 86400000) }
function dateLabel(date) { const d = daysUntil(date); if (d < 0) return `${Math.abs(d)} day${Math.abs(d) !== 1 ? 's' : ''} overdue`; if (d === 0) return "Due today"; if (d === 1) return "Due tomorrow"; return `Due ${new Date(date + "T00:00:00").toLocaleDateString("en-GB", { day: "numeric", month: "short" })}` }
function taskCard(t, mini = false) { return `<article class="${mini ? 'task-mini' : 'task-item'} ${t.completed ? 'completed' : ''}">${mini ? '' : `<input class="task-check" type="checkbox" data-toggle="${t.id}" ${t.completed ? 'checked' : ''} aria-label="Mark task complete">`}<div><h3>${escapeHTML(t.title)}</h3><p>${escapeHTML(t.module)} · ${dateLabel(t.date)}</p></div><div class="task-actions"><span class="badge ${t.priority.toLowerCase()}">${t.priority}</span>${mini ? '' : `<button class="delete-button" data-delete="${t.id}" aria-label="Delete task">Delete</button>`}</div></article>` }
function escapeHTML(s) { return s.replace(/[&<>'"]/g, c => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[c])) }
function bindTasks() { $$('[data-toggle]').forEach(x => x.onchange = () => { const t = tasks.find(t => t.id === +x.dataset.toggle); t.completed = x.checked; store.set("studybalance_tasks", tasks); renderAll(); toast(t.completed ? "Task completed — well done!" : "Task moved back to pending") }); $$('[data-delete]').forEach(x => x.onclick = () => { if (confirm("Delete this task?")) { tasks = tasks.filter(t => t.id !== +x.dataset.delete); store.set("studybalance_tasks", tasks); renderAll(); toast("Task deleted") } }) }
function renderTasks() { const q = $("#taskSearch").value.toLowerCase(), f = $("#taskFilter").value; const filtered = tasks.filter(t => (t.title.toLowerCase().includes(q) || t.module.toLowerCase().includes(q)) && (f === "all" || (f === "pending" && !t.completed) || (f === "completed" && t.completed) || (f === "high" && t.priority === "High"))); $("#taskList").innerHTML = filtered.length ? filtered.map(t => taskCard(t)).join("") : '<div class="panel empty">No matching tasks. Add a task to get started.</div>'; bindTasks() }
$("#taskSearch").oninput = renderTasks; $("#taskFilter").onchange = renderTasks;
function renderDeadlines() { const pending = tasks.filter(t => !t.completed), groups = { overdue: pending.filter(t => daysUntil(t.date) < 0), today: pending.filter(t => daysUntil(t.date) === 0), upcoming: pending.filter(t => daysUntil(t.date) > 0).sort((a, b) => a.date.localeCompare(b.date)) }; for (const [key, list] of Object.entries(groups)) $(`#${key}Tasks`).innerHTML = list.length ? list.map(t => `<article class="deadline-item"><span class="badge ${t.priority.toLowerCase()}">${t.priority}</span><h3>${escapeHTML(t.title)}</h3><p>${escapeHTML(t.module)}</p><p>${dateLabel(t.date)}</p></article>`).join("") : '<p class="empty">Nothing here.</p>' }
function renderStats() { const done = tasks.filter(t => t.completed).length, total = tasks.length, pct = total ? Math.round(done / total * 100) : 0; $("#totalStat").textContent = total; $("#pendingStat").textContent = total - done; $("#completedStat").textContent = done; $("#sessionsStat").textContent = sessions; $("#sessionCount").textContent = sessions; $("#ringValue").textContent = pct + "%"; $("#progressRing").style.background = `conic-gradient(var(--purple) ${pct}%,#e8e9f0 ${pct}%)`; $("#progressBar").style.width = pct + "%"; $("#progressPercent").textContent = pct + "%"; $("#progressDetail").textContent = total ? `${done} of ${total} tasks completed.` : "No tasks added yet."; $("#progressMessage").textContent = total ? (pct === 100 ? "Everything complete — excellent work!" : `${total - done} task${total - done !== 1 ? 's' : ''} still to go.`) : "Add a task to begin."; const upcoming = tasks.filter(t => !t.completed).sort((a, b) => a.date.localeCompare(b.date)).slice(0, 3); $("#dashboardTasks").innerHTML = upcoming.length ? upcoming.map(t => taskCard(t, true)).join("") : '<div class="empty">No upcoming tasks. Enjoy the clear space!</div>' }
function renderAll() { renderTasks(); renderStats(); renderDeadlines() }
function updateTimer() { const m = String(Math.floor(timerSeconds / 60)).padStart(2, "0"), s = String(timerSeconds % 60).padStart(2, "0"); $("#timerDisplay").textContent = `${m}:${s}`; document.title = timerRunning ? `${m}:${s} | StudyBalance` : "StudyBalance | Student Study Planner" }
$("#startTimer").onclick = () => { if (timerRunning) { clearInterval(timerId); timerRunning = false; $("#startTimer").textContent = "Resume"; return } timerRunning = true; $("#startTimer").textContent = "Pause"; timerId = setInterval(() => { timerSeconds--; updateTimer(); if (timerSeconds <= 0) { clearInterval(timerId); timerRunning = false; const focus = $('.timer-mode.active').dataset.minutes === "25"; if (focus) { sessions++; store.set("studybalance_sessions", sessions); renderStats() } toast(focus ? "Focus session complete! Take a break." : "Break finished. Ready to focus?"); timerSeconds = +$('.timer-mode.active').dataset.minutes * 60; $("#startTimer").textContent = "Start"; updateTimer() } }, 1000) };
$("#resetTimer").onclick = () => { clearInterval(timerId); timerRunning = false; timerSeconds = +$('.timer-mode.active').dataset.minutes * 60; $("#startTimer").textContent = "Start"; updateTimer() }; $$('.timer-mode').forEach(b => b.onclick = () => { clearInterval(timerId); timerRunning = false; $$('.timer-mode').forEach(x => x.classList.remove('active')); b.classList.add('active'); timerSeconds = +b.dataset.minutes * 60; $("#startTimer").textContent = "Start"; updateTimer() });
const savedMood = store.get("studybalance_mood", null); function selectMood(m) { $$('[data-mood]').forEach(b => b.classList.toggle('selected', b.dataset.mood === m)); $("#moodMessage").textContent = m ? `Today's check-in: ${m}. Remember to be kind to yourself.` : "" } if (savedMood) selectMood(savedMood); $$('[data-mood]').forEach(b => b.onclick = () => { store.set("studybalance_mood", b.dataset.mood); selectMood(b.dataset.mood); toast("Mood check-in saved") });
renderAll(); updateTimer();
